# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('url', models.TextField(default='http://www.mperc.in/consolidated-reg.htm', max_length=1000)),
                ('xpath', models.TextField(default='/html/body/table/tbody/tr/td/div/center/table[1]/tbody/tr/td[6]/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr[2]/td[69]', max_length=1000)),
                ('modified', models.CharField(default='Today', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.Sector'),
        ),
    ]
