# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-29 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_auto_20200729_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='power.Person'),
            preserve_default=False,
        ),
    ]
