# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-29 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0003_board_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
