# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0004_person_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='modified',
            field=models.CharField(default='Today', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='aadhar',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='mob',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
