# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0005_auto_20200730_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('bid', models.IntegerField()),
            ],
        ),
    ]
