# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-31 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='url',
            field=models.TextField(default='http://www.mperc.in/consolidated-reg.htm', max_length=1000),
        ),
        migrations.AddField(
            model_name='board',
            name='xpath',
            field=models.TextField(default='/html/body/table/tbody/tr/td/div/center/table[1]/tbody/tr/td[6]/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr[2]/td[69]', max_length=1000),
        ),
    ]
