# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-01 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0007_auto_20200731_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadhar',
            field=models.CharField(default='000012340000', max_length=12),
        ),
    ]
