# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0008_auto_20200801_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField(default='https://www.upsldc.org/real-time-data', max_length=1000)),
                ('xpath', models.TextField(default='/html/body/div[2]/div[2]/div/div/div/div/div/div/div/div[1]/div/div/div/div[2]/div/div/div[2]/table', max_length=1000)),
            ],
        ),
    ]
