# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-03 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0009_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='uid',
            field=models.IntegerField(default=2),
        ),
    ]
