# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0010_table_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=2)),
                ('name', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('endtime', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('avgvalue', models.CharField(max_length=100)),
                ('minmattr', models.CharField(max_length=100)),
                ('minmvalue', models.CharField(max_length=100)),
                ('maxmattr', models.CharField(max_length=100)),
                ('maxmvalue', models.CharField(max_length=100)),
            ],
        ),
    ]
