# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0011_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='attr',
            field=models.IntegerField(default=0),
        ),
    ]
