# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actual_flow_min', models.IntegerField()),
                ('Frequency_min', models.IntegerField()),
                ('Date_updated', models.TextField()),
            ],
        ),
    ]
