# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-02 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_electricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='Actual_flow_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricity',
            name='Frequency_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='Actual_flow_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='Frequency_min',
            field=models.IntegerField(default=0),
        ),
    ]
